package it.polito.applied.smiled.pojo;

public enum LogType {
	NEW_POST, ADD_LIKE_POST, DEL_LIKE_POST, UP_POST, DEL_POST,
	NEW_COMM, MODIFY_COMM, DEL_COMM, ADD_LIKE_COMM, DEL_LIKE_COMM, UP_COMM,
	NEW_META_COMM, UP_META_COMM, DEL_META_COMM, ADD_LIKE_META_COMM, DEL_LIKE_META_COMM,
	UP_MISSION_SCEN, UP_MISSION_CHAR, DEL_MISSION_SCEN, DEL_MISSION_CHAR,
	NEW_TRUST_FILE, DEL_TRUST_FILE, UP_TRUST_FILE,
	NEW_CHAR, NEW_ASSOCIATION, NEW_ATTENDEE, NEW_COLLAB, DEL_ATTENDEE, DEL_COLLAB, DEL_CHAR, DEL_ASSOCIATION,
	NEW_SCEN, DEL_SCEN, UP_SCEN_INFO, UP_SCEN_COVER, UP_SCEN_MAP, 
	UP_CHAR_INFO, UP_CHAR_COVER, UP_CHAR_COVER_L,
	UP_USER_INFO, UP_USER_COVER, UP_USER_COVER_L, CHANGE_PWD,
	REG_S, REG_T,
	
	//log relativi a newspaper --->
	NEW_NEWSPAPER, DEL_NEWSPAPER, UP_NEWSPAPER, PUBLISH_NEWSPAPER, ADD_JOURNALIST, DEL_JOURNALIST, UPD_ARTICLE, NEWSPAPER_ON, NEWSPAPER_OFF;
	
	//TODO aggiungere gestione REVISION
}
